b *_IO_file_finish
b *_IO_file_overflow
b *_IO_file_underflow
b *_IO_default_uflow
b *_IO_default_pbackfail
b *_IO_file_xsputn
b *__GI__IO_file_xsgetn
b *_IO_file_seekoff
b *_IO_default_seekpos
b *_IO_file_setbuf
b *_IO_file_sync
b *_IO_file_doallocate
b *_IO_file_read
b *_IO_file_write
b *_IO_file_seek
b *_IO_file_close
b *_IO_file_stat
b *_IO_default_showmanyc
b *_IO_default_imbue
